spring.application.name=svc-evaluation
server.port=8084

server.compression.enabled=true
server.compression.mime-types=application/json,text/plain,application/pdf
server.compression.min-response-size=1024

spring.datasource.url=jdbc:postgresql://localhost:5444/evaluation_rh_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.default_batch_fetch_size=16
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.tool.hbm2ddl=DEBUG
logging.level.org.hibernate.SQL=DEBUG

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/oauth2/jwks

spring.kafka.bootstrap-servers=127.0.0.1:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

evaluation.alert.seuil-insuffisant=3
evaluation.archive.local-root=target/evaluations-archive
evaluation.archive.s3-bucket=rh-evaluations
evaluation.archive.s3-prefix=evaluations
evaluation.referentiel.base-url=http://localhost:8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized
