package com.hr.presence.domain;

public enum PointageStatut {
	VALIDE,
	REJETE_QR_INVALIDE,
	REJETE_QR_EXPIRE,
	REJETE_QR_REVOQUE,
	REJETE_HORS_ZONE,
	REJETE_SITE_INACTIF,
	REJETE_EMPLACEMENT_ABSENT,
	REJETE_PRECISION_GPS
}
